//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace GrainInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ChatUserFactory
    {
        

                        public static GrainInterfaces.IChatUser GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(GrainInterfaces.IChatUser), 1881073148, primaryKey));
                        }

                        public static GrainInterfaces.IChatUser GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(GrainInterfaces.IChatUser), 1881073148, primaryKey, grainClassNamePrefix));
                        }

                        public static GrainInterfaces.IChatUser GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(GrainInterfaces.IChatUser), 1881073148, primaryKey));
                        }

                        public static GrainInterfaces.IChatUser GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(GrainInterfaces.IChatUser), 1881073148, primaryKey, grainClassNamePrefix));
                        }

            public static GrainInterfaces.IChatUser Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ChatUserReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("GrainInterfaces.GrainInterfaces.IChatUser")]
        internal class ChatUserReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, GrainInterfaces.IChatUser
        {
            

            public static GrainInterfaces.IChatUser Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (GrainInterfaces.IChatUser) global::Orleans.Runtime.GrainReference.CastInternal(typeof(GrainInterfaces.IChatUser), (global::Orleans.Runtime.GrainReference gr) => { return new ChatUserReference(gr);}, grainRef, 1881073148);
            }
            
            protected internal ChatUserReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ChatUserReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1881073148;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "GrainInterfaces.GrainInterfaces.IChatUser";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ChatUserReference input = ((ChatUserReference)(original));
                return ((ChatUserReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ChatUserReference input = ((ChatUserReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ChatUserReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ChatUserMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task GrainInterfaces.IChatUser.SendMessage(System.Guid receiver, string message)
            {

                return base.InvokeMethodAsync<object>(1824972864, new object[] {receiver, message} );
            }
            
            System.Threading.Tasks.Task GrainInterfaces.IChatUser.ReceiveMessage(System.Guid sender, string message)
            {

                return base.InvokeMethodAsync<object>(1569111363, new object[] {sender, message} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("GrainInterfaces.GrainInterfaces.IChatUser", 1881073148)]
    internal class ChatUserMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1881073148;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1881073148:  // IChatUser
                        switch (methodId)
                        {
                            case 1824972864: 
                                return ((IChatUser)grain).SendMessage((Guid)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1569111363: 
                                return ((IChatUser)grain).ReceiveMessage((Guid)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1881073148:  // IChatUser
                    switch (methodId)
                    {
                        case 1824972864:
                            return "SendMessage";
                    case 1569111363:
                            return "ReceiveMessage";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
